### PR TITLE
Remove log rotation from disk backend

### PR DESCRIPTION
**Pull request by markyen**
So that the log rotator can recognize them as log files

@jwolski @Raynos

### CODE REVIEW

**Comment by jwolski** [comment]
I think this'll cause logrotate to generate a file like: 'rt-geospatial-yyyyMMdd.log-yyyyMMdd' which would be slightly weird. what about specifying `''` as the datePattern?

**Comment by jwolski** [comment]
And since this is open source and all, does this allow applications to plumb through a date pattern?

**Comment by markyen** [comment]
Hmm, I see. Sounds like we don't want logtron handling log rotation at all, we just want to let `logrotate` handle it. I've updated the PR to remove log rotation entirely.

**Comment by rhugh** [comment]
Just want to make sure I understand the change, since I'm not overly familiar with JS.. what's the expected action from logrotate?  E.g. should it truncate the file so the fd is preserved, trigger an event so a new fd is opened, or will the code now detect the file is missing and create a new file/fd?

**Comment by markyen** [comment]
@rhugh I believe that logrotate will truncate the file, preserving the existing FD

**Comment by rhugh** [comment]
That's the current model, just want to verify that's required.  (It's the most expensive method, for I/O, so wasn't sure if this is meant to change that.)

**Comment by Raynos** [comment]
can we rename the file in a seperate commit; it's hard to review.

**Comment by Raynos** [comment]
Will the log rotation tool run on all servers ? this is used by everyone.

**Comment by Raynos** [comment]
Ideally we should just create a new backend; or bump the major.

**Comment by markyen** [comment]
I see. I suppose this may be too intrusive of a change to apply it to all users. I'll abandon this PR and make the change in configuration instead then.

**Pull request closed without merging**
